console.log("My name is Anuradha Aldar")
console.log( "My hobbies:- 1.Reading  2.Cooking 3.travlling")
console.info("Strength:- 1.Hard Worker  2.Qucik learner 3.")
console.warn("Weakness: 1.Emotional 2.Sensitive 3.Over Thinker")
console.log(30+50)
console.log(49*479)